/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_derek_live_JniPush_Pusher */

#ifndef _Included_com_derek_live_JniPush_Pusher
#define _Included_com_derek_live_JniPush_Pusher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_derek_live_JniPush_Pusher
 * Method:    startPush
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_derek_live_JniPush_Pusher_startPush
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_derek_live_JniPush_Pusher
 * Method:    stopPush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_derek_live_JniPush_Pusher_stopPush
  (JNIEnv *, jobject);

/*
 * Class:     com_derek_live_JniPush_Pusher
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_derek_live_JniPush_Pusher_release
  (JNIEnv *, jobject);

/*
 * Class:     com_derek_live_JniPush_Pusher
 * Method:    setVideoOptions
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_derek_live_JniPush_Pusher_setVideoOptions
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_derek_live_JniPush_Pusher
 * Method:    setAudioOptions
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_derek_live_JniPush_Pusher_setAudioOptions
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_derek_live_JniPush_Pusher
 * Method:    fireVideo
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_derek_live_JniPush_Pusher_fireVideo
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_derek_live_JniPush_Pusher
 * Method:    fireAudio
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_derek_live_JniPush_Pusher_fireAudio
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
